name: Build and Release EXE

on:
  push:
    tags:
      - '*'  # Uruchamia workflow na każdym nowym tagu

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Clean previous builds
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }
          if (Test-Path dist) { Remove-Item -Recurse -Force dist }
          if (Test-Path __pycache__) { Remove-Item -Recurse -Force __pycache__ }
        shell: pwsh

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed script_to_csv.py

      - name: Show dist folder contents
        run: dir dist

      - name: Install GitHub CLI
        run: |
          choco install gh
        shell: cmd

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        shell: bash

      - name: Create Release and Upload Asset
        run: |
          gh release create ${{ github.ref_name }} dist/script_to_csv.exe --title "Release ${{ github.ref_name }}" --notes "Automatycznie wygenerowany release"
        shell: bash